/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author RIFQI
 */
public class MainMenu extends javax.swing.JFrame {
    // waktu sekarang 
     private void setJam(){
        ActionListener listener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                jam.setText(new WaktuSekarang().getWkt());
            }
        };
        new Timer(1000, listener).start();
    }
    
    public MainMenu() {
        setJam();
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new javax.swing.JPanel();
        panelmenu = new javax.swing.JPanel();
        bhome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bpekerjaan = new javax.swing.JButton();
        bhasil = new javax.swing.JButton();
        btentang = new javax.swing.JButton();
        panelwaktu = new javax.swing.JPanel();
        jam = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        panelmain = new javax.swing.JPanel();
        panelhome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        paneldatapekerjaan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelhasil = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemilihan Pekerjaan ME");

        panelutama.setBackground(new java.awt.Color(0, 153, 153));

        panelmenu.setBackground(new java.awt.Color(0, 153, 153));
        panelmenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        bhome.setBackground(new java.awt.Color(0, 204, 102));
        bhome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/home.png"))); // NOI18N
        bhome.setText("HOME");
        bhome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhomeMouseExited(evt);
            }
        });
        bhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhomeActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("logo panca");

        bpekerjaan.setBackground(new java.awt.Color(0, 204, 102));
        bpekerjaan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bpekerjaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/pekerjaan-transformed.png"))); // NOI18N
        bpekerjaan.setText("DATA PEKERJAAN");
        bpekerjaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bpekerjaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bpekerjaanMouseExited(evt);
            }
        });
        bpekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpekerjaanActionPerformed(evt);
            }
        });

        bhasil.setBackground(new java.awt.Color(0, 204, 102));
        bhasil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bhasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/hasil-transformed.png"))); // NOI18N
        bhasil.setText("HASIL");
        bhasil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bhasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bhasilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bhasilMouseExited(evt);
            }
        });
        bhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhasilActionPerformed(evt);
            }
        });

        btentang.setBackground(new java.awt.Color(0, 204, 102));
        btentang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/about.png"))); // NOI18N
        btentang.setText("TENTANG");
        btentang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btentangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btentangMouseExited(evt);
            }
        });

        panelwaktu.setBackground(new java.awt.Color(255, 0, 0));

        jam.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jam.setForeground(new java.awt.Color(255, 255, 255));
        jam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tgl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        tgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelwaktuLayout = new javax.swing.GroupLayout(panelwaktu);
        panelwaktu.setLayout(panelwaktuLayout);
        panelwaktuLayout.setHorizontalGroup(
            panelwaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelwaktuLayout.setVerticalGroup(
            panelwaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelwaktuLayout.createSequentialGroup()
                .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jam.setText(new WaktuSekarang().getWkt());
        jam.setPreferredSize(new java.awt.Dimension(100,22));
        tgl.setText(new WaktuSekarang().getTgl());
        tgl.setPreferredSize(new java.awt.Dimension(120,22));

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bpekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bhasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btentang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelwaktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(bhome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(bhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btentang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(panelwaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelmain.setBackground(new java.awt.Color(0, 153, 153));
        panelmain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        panelmain.setLayout(new java.awt.CardLayout());

        panelhome.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setText("HOME");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout panelhomeLayout = new javax.swing.GroupLayout(panelhome);
        panelhome.setLayout(panelhomeLayout);
        panelhomeLayout.setHorizontalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelhomeLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelhomeLayout.setVerticalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhomeLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelhomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelhomeLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 194, Short.MAX_VALUE))
        );

        panelmain.add(panelhome, "card2");

        paneldatapekerjaan.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setText("data pekerjaan");

        javax.swing.GroupLayout paneldatapekerjaanLayout = new javax.swing.GroupLayout(paneldatapekerjaan);
        paneldatapekerjaan.setLayout(paneldatapekerjaanLayout);
        paneldatapekerjaanLayout.setHorizontalGroup(
            paneldatapekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldatapekerjaanLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        paneldatapekerjaanLayout.setVerticalGroup(
            paneldatapekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldatapekerjaanLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        panelmain.add(paneldatapekerjaan, "card3");

        panelhasil.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setText("hasil");

        javax.swing.GroupLayout panelhasilLayout = new javax.swing.GroupLayout(panelhasil);
        panelhasil.setLayout(panelhasilLayout);
        panelhasilLayout.setHorizontalGroup(
            panelhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhasilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(645, Short.MAX_VALUE))
        );
        panelhasilLayout.setVerticalGroup(
            panelhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhasilLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 398, Short.MAX_VALUE))
        );

        panelmain.add(panelhasil, "card4");

        javax.swing.GroupLayout panelutamaLayout = new javax.swing.GroupLayout(panelutama);
        panelutama.setLayout(panelutamaLayout);
        panelutamaLayout.setHorizontalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelutamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelutamaLayout.setVerticalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelutamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhomeActionPerformed
        //remove panel
        panelmain.removeAll();
        panelmain.repaint();
        panelmain.revalidate();
        //add panel
        panelmain.add(panelhome);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_bhomeActionPerformed

    private void bpekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpekerjaanActionPerformed
        //remove panel
        panelmain.removeAll();
        panelmain.repaint();
        panelmain.revalidate();
        //add panel
        panelmain.add(paneldatapekerjaan);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_bpekerjaanActionPerformed

    private void bhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhasilActionPerformed
        panelmain.removeAll();
        panelmain.repaint();
        panelmain.revalidate();
        //add panel
        panelmain.add(panelhasil);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_bhasilActionPerformed

    private void bhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhomeMouseEntered
        bhome.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_bhomeMouseEntered

    private void bhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhomeMouseExited
        bhome.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_bhomeMouseExited

    private void bpekerjaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpekerjaanMouseEntered
        bpekerjaan.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_bpekerjaanMouseEntered

    private void bpekerjaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpekerjaanMouseExited
        bpekerjaan.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_bpekerjaanMouseExited

    private void bhasilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhasilMouseEntered
        bhasil.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_bhasilMouseEntered

    private void bhasilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bhasilMouseExited
        bhasil.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_bhasilMouseExited

    private void btentangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btentangMouseEntered
        btentang.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_btentangMouseEntered

    private void btentangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btentangMouseExited
        btentang.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btentangMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhasil;
    private javax.swing.JButton bhome;
    private javax.swing.JButton bpekerjaan;
    private javax.swing.JButton btentang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel jam;
    private javax.swing.JPanel paneldatapekerjaan;
    private javax.swing.JPanel panelhasil;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panelmain;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JPanel panelutama;
    private javax.swing.JPanel panelwaktu;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
